---
name: CMPSC 302 Open
break: true
indent: 4
---

docs/style/play.css:
    MatchFileFragment --fragment "TODO" --count 0 --exact --description "[CSS] play.css contains no TODOs"

ExecuteCommand "html5validator --root docs/" --description "[HTML] The docs/ directory passes W3C validation"
ExecuteCommand "html5validator --root docs/ --skip-non-css" --description "[CSS] The docs/ directory passes W3C validation"
ExecuteCommand "python config/.selenium.py hole-1.html" --description "[GOLF] Hole 1 complete"
ExecuteCommand "python config/.selenium.py hole-2.html" --description "[GOLF] Hole 2 complete"
