---
name: CMPSC 302 Open
break: true
indent: 4
---

docs/style/play.css:
    MatchFileFragment --fragment "TODO" --count 0 --exact --description "[CSS] play.css contains no TODOs"

ExecuteCommand --command "html5validator --root docs/" --description "[HTML] The docs/ directory passes W3C validation"
ExecuteCommand --command "html5validator --root docs/style/play.css --skip-non-css" --description "[CSS] The docs/ directory passes W3C validation"
ExecuteCommand --command "python config/.selenium.py hole-1.html" --description "[GOLF] Hole 1 complete"
ExecuteCommand --command "python config/.selenium.py hole-2.html" --description "[GOLF] Hole 2 complete"
ExecuteCommand --command "python config/.selenium.py hole-3.html" --description "[GOLF] Hole 3 complete"
ExecuteCommand --command "python config/.selenium.py hole-4.html" --description "[GOLF] Hole 3 complete"
ExecuteCommand --command "python config/.selenium.py hole-5.html" --description "[GOLF] Hole 3 complete"
ExecuteCommand --command "python config/.selenium.py hole-6.html" --description "[GOLF] Hole 3 complete"
ExecuteCommand --command "python config/.selenium.py hole-7.html" --description "[GOLF] Hole 3 complete"
ExecuteCommand --command "python config/.selenium.py hole-8.html" --description "[GOLF] Hole 3 complete"
ExecuteCommand --command "python config/.selenium.py hole-9.html" --description "[GOLF] Hole 3 complete"
