---
name: CMPSC 302 Open
break: true
indent: 4
---

docs/style/play.css:
  MatchFileFragment --fragment "TODO" --count 0 --exact --description "[CSS] play.css contains no TODOs"

ExecuteCommand "python config/.selenium.py hole-1.html" --description "[GOLF] Hole 1 complete"
