  name: GatorGrader

  on:
    push:
      branches: [ main ]

  env:
    GWIZ_TOKEN: ${{ secrets.GWIZ_TOKEN }}

  jobs:
    grade:
      runs-on: ubuntu-latest
      services:
        selenium:
          image: selenium/standalone-chrome
      steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: '0'
      - name: Setup Python
        if: always()
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: nanasess/setup-chromedriver@master
      - name: Set up grading environment
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --three
          pip install bs4
          pip install requests
          pip install html5validator
      - name: Grade repository
        run: |
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1
          html5validator --root docs/
          python config/.selenium.py
        if: always()
        env:   
         PIPENV_VENV_IN_PROJECT: 1
         PIPENV_IGNORE_VIRTUALENVS: 1


